### PR TITLE
[Task][27049] [Manager] Tìm kiếm

### PR DESCRIPTION
**Pull request by nguyenvd16**
search
https://edu-redmine.sun-asterisk.vn/issues/27049

### CODE REVIEW

**Review by nguyennhathai — APPROVED** [review]

**Comment by nguyenvd16** [comment]
search-2

**Comment by nguyenvd16** [comment]
ready

**Comment by nguyenvd16** [comment]
Screenshot from 2020-09-04 14-16-10

**Comment by nguyenvd16** [comment]
ready

**Comment by nguyenvd16** [comment]
Screenshot from 2020-09-04 14-30-03

**Comment by nguyenvd16** [comment]
ready

**Pull request merged**
